#!/bin/bash

clear

# Colors
RED='\033[0;31m'
GRN='\033[0;32m'
CYN='\033[0;36m'
YEL='\033[1;33m'
NC='\033[0m' # No Color

# Banner
echo -e "${YEL}"
cat << "EOF"
 /$$$$$$$$       /$$     /$$       /$$   /$$       /$$$$$$$$       /$$   /$$
|_____ $$       |  $$   /$$/      | $$$ | $$      | $$_____/      | $$  / $$
     /$$/        \  $$ /$$/       | $$$$| $$      | $$            |  $$/ $$/
    /$$/          \  $$$$/        | $$ $$ $$      | $$$$$          \  $$$$/ 
   /$$/            \  $$/         | $$  $$$$      | $$__/           >$$  $$ 
  /$$/              | $$          | $$\  $$$      | $$             /$$/\  $$
 /$$$$$$$$          | $$          | $$ \  $$      | $$$$$$$$      | $$  \ $$
|________/          |__/          |__/  \__/      |________/      |__/  |__/
EOF
echo -e "${NC}"

# Subscription Prompt
echo -e "${GRN}:fire: Please Subscribe \n${NC}"

for i in {1..3}; do
  echo -ne "${CYN}Subscribing To ZYNEXCODE"
  for dot in {1..3}; do
    echo -n "."
    sleep 0.3
  done
  echo -ne "\r\033[K"  # Clear line for smooth animation
done

echo -e "${GRN}:white_check_mark: Thanks for Subscribing! If Not, Do It Now :rocket:${NC}\n"
sleep 1
#!/bin/bash


# Install fastfetch
echo "Installing fastfetch..."
wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.32.1/fastfetch-linux-amd64.deb && apt install ./fastfetch-linux-amd64.deb

# Run Neofetch to display system information
echo "Running fastfetch..."
fastfetch

echo "All tasks completed successfully!"
